# Generated by Django 5.2.18 on 2026-10-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='is_manual',
            field=models.BooleanField(default=False),
        ),
    ]
