# Generated by Django 5.2.18 on 2026-10-09 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_flight_is_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='share_token',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True),
        ),
    ]
