# Generated by Django 5.2.18 on 2026-10-09 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_user_share_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='traveler_name',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
